dbt_demo:
  outputs:
    dev:
      type: snowflake
      account: vz97431.west-europe.azure
      # User/password auth
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD')}}"
      role: SYSADMIN
      database: DBT_DEMO
      warehouse: STANDARD_XS
      schema: DBT
  target: dev